FROM node:10.15-alpine

ENV HOST 0.0.0.0
ENV APP_ROOT /usr/src/api

# RUN mkdir -p ${APP_ROOT}
WORKDIR ${APP_ROOT}

COPY ./api/package.json .

# RUN apk --no-cache add --virtual builds-deps build-base python

# Install nodemon globallybcryptjs
#RUN npm install -g cnpm --registry=https://registry.npm.taobao.org \
#&& cnpm install -g nodemon \
#&& cnpm install -g knex \
#&& cnpm install \
#&& cnpm rebuild bcrypt --build-from-source
RUN npm install -g nodemon \
&& npm install -g knex \
&& npm install \
&& npm rebuild bcrypt --build-from-source

EXPOSE 8080