name: Docker Image CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v1
            - name: Build the docker-compose stack
              run: docker-compose -f docker-compose.ci.yml build
            - name: up containers
              run: docker-compose -f docker-compose.ci.yml -p react-demo up -d
            - name: Check running containers
              run: docker ps -a
            - name: Check logs
              run: docker logs backend
            - name: Run test suite
              run: docker exec backend pytest --skip-auth

